
services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Lab1/Dockerfile
    # networks:
    #   - app-network

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx-lb
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   networks:
  #     - app-network

  provider:
    container_name: provider
    image: ${DOCKER_REGISTRY-}grpcservice
    build:
      context: .
      dockerfile: GrpcService/Dockerfile
    # networks:
    #   - app-network

# networks:
#   app-network:
#     driver: bridge
